
name: Continuous Integration

on:
#  pull_request:
#    branches: [docs]
  push:
    branches: [docs]

jobs:
  build:
    name: Generate docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch (fast)
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Cache ivy2
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Cache coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-sbt-coursier-cache-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Cache sbt
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-cache-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Cache yarn
        uses: actions/cache@v1
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}

      - name: Build
        run: ./build.sh

      - name: Artifact
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: website/build/

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build/cats-effect
          publish_branch: test-gh-pages