
name: Continuous Integration

on:
#  pull_request:
#    branches: [docs]
  push:
    branches: [docs]

#env:
#  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Generate docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch (fast)
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - run: ./build.sh